FROM node:18-alpine

WORKDIR /app

# package.json ve package-lock.json'ı kopyala
COPY package*.json ./

# Bağımlılıkları yükle
RUN npm install

# Uygulama dosyalarını kopyala
COPY . .

# Port
EXPOSE 5173w

# Development server'ı başlat
CMD ["npm", "run", "dev", "--", "--host"]

